// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#ifndef PROTOBUF_login_2eproto__INCLUDED
#define PROTOBUF_login_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace csmsg {
class TMSG_LOGIN_REQ;
class TMSG_LOGIN_REQDefaultTypeInternal;
extern TMSG_LOGIN_REQDefaultTypeInternal _TMSG_LOGIN_REQ_default_instance_;
class TMSG_LOGIN_RSP;
class TMSG_LOGIN_RSPDefaultTypeInternal;
extern TMSG_LOGIN_RSPDefaultTypeInternal _TMSG_LOGIN_RSP_default_instance_;
}  // namespace csmsg

namespace csmsg {

namespace protobuf_login_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_login_2eproto

// ===================================================================

class TMSG_LOGIN_REQ : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csmsg.TMSG_LOGIN_REQ) */ {
 public:
  TMSG_LOGIN_REQ();
  virtual ~TMSG_LOGIN_REQ();

  TMSG_LOGIN_REQ(const TMSG_LOGIN_REQ& from);

  inline TMSG_LOGIN_REQ& operator=(const TMSG_LOGIN_REQ& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TMSG_LOGIN_REQ& default_instance();

  static inline const TMSG_LOGIN_REQ* internal_default_instance() {
    return reinterpret_cast<const TMSG_LOGIN_REQ*>(
               &_TMSG_LOGIN_REQ_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TMSG_LOGIN_REQ* other);

  // implements Message ----------------------------------------------

  inline TMSG_LOGIN_REQ* New() const PROTOBUF_FINAL { return New(NULL); }

  TMSG_LOGIN_REQ* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TMSG_LOGIN_REQ& from);
  void MergeFrom(const TMSG_LOGIN_REQ& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TMSG_LOGIN_REQ* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string strUserName = 2;
  bool has_strusername() const;
  void clear_strusername();
  static const int kStrUserNameFieldNumber = 2;
  const ::std::string& strusername() const;
  void set_strusername(const ::std::string& value);
  #if LANG_CXX11
  void set_strusername(::std::string&& value);
  #endif
  void set_strusername(const char* value);
  void set_strusername(const char* value, size_t size);
  ::std::string* mutable_strusername();
  ::std::string* release_strusername();
  void set_allocated_strusername(::std::string* strusername);

  // required string strPassword = 3;
  bool has_strpassword() const;
  void clear_strpassword();
  static const int kStrPasswordFieldNumber = 3;
  const ::std::string& strpassword() const;
  void set_strpassword(const ::std::string& value);
  #if LANG_CXX11
  void set_strpassword(::std::string&& value);
  #endif
  void set_strpassword(const char* value);
  void set_strpassword(const char* value, size_t size);
  ::std::string* mutable_strpassword();
  ::std::string* release_strpassword();
  void set_allocated_strpassword(::std::string* strpassword);

  // required uint32 nUserData = 1;
  bool has_nuserdata() const;
  void clear_nuserdata();
  static const int kNUserDataFieldNumber = 1;
  ::google::protobuf::uint32 nuserdata() const;
  void set_nuserdata(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:csmsg.TMSG_LOGIN_REQ)
 private:
  void set_has_nuserdata();
  void clear_has_nuserdata();
  void set_has_strusername();
  void clear_has_strusername();
  void set_has_strpassword();
  void clear_has_strpassword();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr strusername_;
  ::google::protobuf::internal::ArenaStringPtr strpassword_;
  ::google::protobuf::uint32 nuserdata_;
  friend struct protobuf_login_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TMSG_LOGIN_RSP : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:csmsg.TMSG_LOGIN_RSP) */ {
 public:
  TMSG_LOGIN_RSP();
  virtual ~TMSG_LOGIN_RSP();

  TMSG_LOGIN_RSP(const TMSG_LOGIN_RSP& from);

  inline TMSG_LOGIN_RSP& operator=(const TMSG_LOGIN_RSP& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TMSG_LOGIN_RSP& default_instance();

  static inline const TMSG_LOGIN_RSP* internal_default_instance() {
    return reinterpret_cast<const TMSG_LOGIN_RSP*>(
               &_TMSG_LOGIN_RSP_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(TMSG_LOGIN_RSP* other);

  // implements Message ----------------------------------------------

  inline TMSG_LOGIN_RSP* New() const PROTOBUF_FINAL { return New(NULL); }

  TMSG_LOGIN_RSP* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TMSG_LOGIN_RSP& from);
  void MergeFrom(const TMSG_LOGIN_RSP& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TMSG_LOGIN_RSP* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 nUserData = 1;
  bool has_nuserdata() const;
  void clear_nuserdata();
  static const int kNUserDataFieldNumber = 1;
  ::google::protobuf::uint32 nuserdata() const;
  void set_nuserdata(::google::protobuf::uint32 value);

  // required int32 nErrCode = 2;
  bool has_nerrcode() const;
  void clear_nerrcode();
  static const int kNErrCodeFieldNumber = 2;
  ::google::protobuf::int32 nerrcode() const;
  void set_nerrcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:csmsg.TMSG_LOGIN_RSP)
 private:
  void set_has_nuserdata();
  void clear_has_nuserdata();
  void set_has_nerrcode();
  void clear_has_nerrcode();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 nuserdata_;
  ::google::protobuf::int32 nerrcode_;
  friend struct protobuf_login_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TMSG_LOGIN_REQ

// required uint32 nUserData = 1;
inline bool TMSG_LOGIN_REQ::has_nuserdata() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TMSG_LOGIN_REQ::set_has_nuserdata() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TMSG_LOGIN_REQ::clear_has_nuserdata() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TMSG_LOGIN_REQ::clear_nuserdata() {
  nuserdata_ = 0u;
  clear_has_nuserdata();
}
inline ::google::protobuf::uint32 TMSG_LOGIN_REQ::nuserdata() const {
  // @@protoc_insertion_point(field_get:csmsg.TMSG_LOGIN_REQ.nUserData)
  return nuserdata_;
}
inline void TMSG_LOGIN_REQ::set_nuserdata(::google::protobuf::uint32 value) {
  set_has_nuserdata();
  nuserdata_ = value;
  // @@protoc_insertion_point(field_set:csmsg.TMSG_LOGIN_REQ.nUserData)
}

// required string strUserName = 2;
inline bool TMSG_LOGIN_REQ::has_strusername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TMSG_LOGIN_REQ::set_has_strusername() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TMSG_LOGIN_REQ::clear_has_strusername() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TMSG_LOGIN_REQ::clear_strusername() {
  strusername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strusername();
}
inline const ::std::string& TMSG_LOGIN_REQ::strusername() const {
  // @@protoc_insertion_point(field_get:csmsg.TMSG_LOGIN_REQ.strUserName)
  return strusername_.GetNoArena();
}
inline void TMSG_LOGIN_REQ::set_strusername(const ::std::string& value) {
  set_has_strusername();
  strusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csmsg.TMSG_LOGIN_REQ.strUserName)
}
#if LANG_CXX11
inline void TMSG_LOGIN_REQ::set_strusername(::std::string&& value) {
  set_has_strusername();
  strusername_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csmsg.TMSG_LOGIN_REQ.strUserName)
}
#endif
inline void TMSG_LOGIN_REQ::set_strusername(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_strusername();
  strusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csmsg.TMSG_LOGIN_REQ.strUserName)
}
inline void TMSG_LOGIN_REQ::set_strusername(const char* value, size_t size) {
  set_has_strusername();
  strusername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csmsg.TMSG_LOGIN_REQ.strUserName)
}
inline ::std::string* TMSG_LOGIN_REQ::mutable_strusername() {
  set_has_strusername();
  // @@protoc_insertion_point(field_mutable:csmsg.TMSG_LOGIN_REQ.strUserName)
  return strusername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TMSG_LOGIN_REQ::release_strusername() {
  // @@protoc_insertion_point(field_release:csmsg.TMSG_LOGIN_REQ.strUserName)
  clear_has_strusername();
  return strusername_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TMSG_LOGIN_REQ::set_allocated_strusername(::std::string* strusername) {
  if (strusername != NULL) {
    set_has_strusername();
  } else {
    clear_has_strusername();
  }
  strusername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strusername);
  // @@protoc_insertion_point(field_set_allocated:csmsg.TMSG_LOGIN_REQ.strUserName)
}

// required string strPassword = 3;
inline bool TMSG_LOGIN_REQ::has_strpassword() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TMSG_LOGIN_REQ::set_has_strpassword() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TMSG_LOGIN_REQ::clear_has_strpassword() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TMSG_LOGIN_REQ::clear_strpassword() {
  strpassword_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_strpassword();
}
inline const ::std::string& TMSG_LOGIN_REQ::strpassword() const {
  // @@protoc_insertion_point(field_get:csmsg.TMSG_LOGIN_REQ.strPassword)
  return strpassword_.GetNoArena();
}
inline void TMSG_LOGIN_REQ::set_strpassword(const ::std::string& value) {
  set_has_strpassword();
  strpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:csmsg.TMSG_LOGIN_REQ.strPassword)
}
#if LANG_CXX11
inline void TMSG_LOGIN_REQ::set_strpassword(::std::string&& value) {
  set_has_strpassword();
  strpassword_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:csmsg.TMSG_LOGIN_REQ.strPassword)
}
#endif
inline void TMSG_LOGIN_REQ::set_strpassword(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_strpassword();
  strpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:csmsg.TMSG_LOGIN_REQ.strPassword)
}
inline void TMSG_LOGIN_REQ::set_strpassword(const char* value, size_t size) {
  set_has_strpassword();
  strpassword_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:csmsg.TMSG_LOGIN_REQ.strPassword)
}
inline ::std::string* TMSG_LOGIN_REQ::mutable_strpassword() {
  set_has_strpassword();
  // @@protoc_insertion_point(field_mutable:csmsg.TMSG_LOGIN_REQ.strPassword)
  return strpassword_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TMSG_LOGIN_REQ::release_strpassword() {
  // @@protoc_insertion_point(field_release:csmsg.TMSG_LOGIN_REQ.strPassword)
  clear_has_strpassword();
  return strpassword_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TMSG_LOGIN_REQ::set_allocated_strpassword(::std::string* strpassword) {
  if (strpassword != NULL) {
    set_has_strpassword();
  } else {
    clear_has_strpassword();
  }
  strpassword_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strpassword);
  // @@protoc_insertion_point(field_set_allocated:csmsg.TMSG_LOGIN_REQ.strPassword)
}

// -------------------------------------------------------------------

// TMSG_LOGIN_RSP

// required uint32 nUserData = 1;
inline bool TMSG_LOGIN_RSP::has_nuserdata() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TMSG_LOGIN_RSP::set_has_nuserdata() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TMSG_LOGIN_RSP::clear_has_nuserdata() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TMSG_LOGIN_RSP::clear_nuserdata() {
  nuserdata_ = 0u;
  clear_has_nuserdata();
}
inline ::google::protobuf::uint32 TMSG_LOGIN_RSP::nuserdata() const {
  // @@protoc_insertion_point(field_get:csmsg.TMSG_LOGIN_RSP.nUserData)
  return nuserdata_;
}
inline void TMSG_LOGIN_RSP::set_nuserdata(::google::protobuf::uint32 value) {
  set_has_nuserdata();
  nuserdata_ = value;
  // @@protoc_insertion_point(field_set:csmsg.TMSG_LOGIN_RSP.nUserData)
}

// required int32 nErrCode = 2;
inline bool TMSG_LOGIN_RSP::has_nerrcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TMSG_LOGIN_RSP::set_has_nerrcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TMSG_LOGIN_RSP::clear_has_nerrcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TMSG_LOGIN_RSP::clear_nerrcode() {
  nerrcode_ = 0;
  clear_has_nerrcode();
}
inline ::google::protobuf::int32 TMSG_LOGIN_RSP::nerrcode() const {
  // @@protoc_insertion_point(field_get:csmsg.TMSG_LOGIN_RSP.nErrCode)
  return nerrcode_;
}
inline void TMSG_LOGIN_RSP::set_nerrcode(::google::protobuf::int32 value) {
  set_has_nerrcode();
  nerrcode_ = value;
  // @@protoc_insertion_point(field_set:csmsg.TMSG_LOGIN_RSP.nErrCode)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace csmsg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_login_2eproto__INCLUDED
